# Generated by Django 6.0.1 on 2026-02-03 07:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('did', models.AutoField(primary_key=True, serialize=False)),
                ('doctor_name', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('dob', models.DateField()),
                ('address', models.TextField()),
                ('qualification', models.CharField(max_length=100)),
                ('experience', models.IntegerField()),
                ('last_worked_hospital', models.CharField(max_length=100)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('wid', models.AutoField(primary_key=True, serialize=False)),
                ('ward_name', models.CharField(max_length=50)),
                ('ward_type', models.CharField(max_length=50)),
                ('ward_mode', models.CharField(max_length=50)),
                ('total_beds', models.IntegerField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('room_type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('patient_name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('address', models.TextField()),
                ('problem', models.CharField(max_length=200)),
                ('admission_date', models.DateTimeField(auto_now_add=True)),
                ('discharge_date', models.DateTimeField(blank=True, null=True)),
                ('is_admitted', models.BooleanField(default=True)),
                ('fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('diagnosis', models.TextField()),
                ('mobile_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('consult_doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to='hospital.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('bid', models.AutoField(primary_key=True, serialize=False)),
                ('diagnosis', models.CharField(max_length=200)),
                ('contact_number', models.CharField(max_length=15)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('bill_date', models.DateTimeField(auto_now_add=True)),
                ('payment_status', models.CharField(choices=[('paid', 'Paid'), ('pending', 'Pending'), ('partial', 'Partial')], default='pending', max_length=20)),
                ('payment_method', models.CharField(blank=True, choices=[('cash', 'Cash'), ('card', 'Card'), ('upi', 'UPI'), ('insurance', 'Insurance'), ('other', 'Other')], max_length=20, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bills_created', to=settings.AUTH_USER_MODEL)),
                ('consult_doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='hospital.patient')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Administrator'), ('doctor', 'Doctor'), ('staff', 'Staff'), ('receptionist', 'Receptionist')], default='staff', max_length=20)),
                ('gender', models.CharField(max_length=10)),
                ('dob', models.DateField()),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=50)),
                ('mobile_no', models.CharField(max_length=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_attendance', models.DateField()),
                ('incoming_time', models.TimeField(blank=True, null=True)),
                ('outgoing_time', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('leave', 'On Leave'), ('half_day', 'Half Day')], default='present', max_length=20)),
                ('task_involved', models.CharField(blank=True, max_length=200)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_of_attendance'],
                'unique_together': {('staff', 'date_of_attendance')},
            },
        ),
    ]
